inseven/opolua

OpoLua/Model/Directory.swift, OpoLua/Model/Program.swift, OpoLua/Utilities/ProgramDetector.swift, OpoLua/View Controllers/Viewers/ImageViewController.swift, swift/OpoInterpreter.swift
I was incorrectly reusing our shared `OpoInterpreter` on multiple threads which would occasionally lead to a crash. To address this, this change removes the shared interpreter and creates a new instance for each scanner queue.
=> fix: Intermittent crashes when scanning for files and programs

OpoLua/View Controllers/LibraryViewController.swift
This was previously 'OPL' and it was confusing as it didn't really describe the purpose of the view.
=> fix: Rename the library to 'Library' (instead of 'OPL')

OpoLua.xcodeproj/project.pbxproj, OpoLua/Extensions/OpoInterpreter+UIKit.swift, OpoLua/Model/Directory.swift, OpoLua/Utilities/DirectoryMonitor.swift, OpoLua/Utilities/ProgramDetector.swift, OpoLua/Utilities/RecursiveDirectoryMonitor.swift
The current mechanism we're using to monitor for file system changes requires us monitor each and every directory in the tree, causing us to open a large number of file handles if users add large directories. This change mitigates the impact of that by introducing a shared monitoring mechanism to ensure that we never watch a directory more than once, even if there are multiple observers for that directory.
The unfortunate side effect of this approach is that we're no longer able to be discrimitate when notifying observers about changes specific to them; we have to inform them of all changes, even if they're outside of their directory tree. That's because if there's ever a symlink in the path (which there often is), we loose the ability to determine if a changed URL is below a given root. …
=> fix: Unnecessary directory monitoring can lead to crashes

OpoLua.xcodeproj/project.pbxproj, OpoLua/AppDelegate.swift, OpoLua/Extensions/FileManager.swift, OpoLua/Model/Directory.swift, OpoLua/Model/Installer.swift, OpoLua/Utilities/IndexableLocationObserver.swift, OpoLua/Utilities/ProgramDetector.swift, OpoLua/Utilities/UbiquitousDownloader.swift, OpoLua/View Controllers/AllProgramsViewController.swift, OpoLua/View Controllers/DirectoryViewController.swift
This change includes a drive-by fix to use the notification center as a belt-and-braces approach to ensure 'All Programs' and the current directory are updated following a successful install.
=> fix: Ensure programs from iCloud Drive automatically appear in 'All Programs'

.github/workflows/build.yaml, ExportOptions.plist, scripts/build.sh, scripts/install-dependencies.sh
This change also updates the versions of changes and build-tools to satisfy the new Pipenv requirement for named sources and removes the install stage for the GitHub CLI (relying instead on the built in one on the runner).
=> ci: Update build for Xcode 14

.github/workflows/build.yaml, scripts/build.sh
This changes removes the explicit `ARCHIVE` and `TEST_FLIGHT_UPLOAD` flags as we always wish to generate archives, and TestFlight uploads are now gated by the `RELEASE` flag.
=> ci: Remove unnecessary build flags

OpoLua/Extensions/CGImage.swift
Which apparently no longer lets you get away with byteOrder32Little in an 8bpp greyscale image.
=> fix: crash in iOS 16

OpoLua/Utilities/RecursiveDirectoryMonitor.swift
It looks like iOS 16 is far more agressive about limiting open file handles meaning we were running out of resources when monitoring large directory structures. This dials the number of open monitors down to 20 from 1000 and relies on manual refresh as a recovery mechanism. Hopefully we can find a better solution in the future.
=> fix: Crash when adding large directories

.github/workflows/build.yaml
Looks like builds don't work on Ventura right now; restoring to Monterey until other build issues have been resolved.
=> ci: Revert to building on macOS Monterey

OpoLua/View Controllers/SettingsView.swift
This updates the website link to go to https://opolua.org instead of https://inseven.co.uk. This is preparatory work for migrating the app to a personal developer account.
=> fix: Update about screen website link

README.md
I missed this when consolidating the workflows.
=> docs: Remove defunct GitHub Actions workflow status badge

src/opl.lua
I think this got broken somewhere in the memory model refactor, either that or it's been broken ever since 6a4bc89...
=> fix: "Close Program" was not setting GETCMD=X correctly

src/menu.lua, src/opl.lua
In particular in MENU calls with menus that have dividing lines in as well as scrollbars, which necessitates supporting smooth scrolling as opposed to only scrolling in multiples of the line height.
Also fixes several graphical glitches in menus with scrollbars, such as submenu arrows not drawing in the correct location, performance, and flicker.
=> fix: better menu scrollbar support

OpoLua.xcodeproj/project.pbxproj, swift/CGImage.swift, swift/OpoInterpreter.swift, swift/OpoIoHandler.swift, swift/OpoIoHandler_CoreGraphics.swift, swift/OpoIoHandler_UIKit.swift
This small change moves towards allowing the OpoLua core functionality to be reused in other projects by marking some functions and classes as public and moving the `CGImage` extensions into the 'swift' directory so this can be use standalone (alongside the 'src' directory which contains the corresponding Lua source).
It's unclear what the long-term approach to allowing code reuse across projects will be, but this allows for initial experimentation.
=> refactor: Enable `OpoInterpreter` reuse in other projects

swift/OplKeyCode.swift, swift/OpoInterpreter.swift, swift/OpoIoHandler.swift
While this isn't directly required for OpoLua, the change is gradually moving towards some kind of ‘core’ library which can be shared between projects.
=> refactor: Make `OpoIoHandler` public to allow reuse in other projects

src/modules/toolbar.lua, src/opl.lua, src/ops.lua, src/runtime.lua
* fixed crash in BikLog5 due to not declaring TbMenuSym%
* fixed lack of EOF error in IOREAD (fixes #213)
* removed null byte from CallProcByStringExpr in dumpopo.lua output (as noted on #328).
* fixed missing OPX info in CallOpxFunc dumpopo.lua output
* "Force close program" now dumps the stacktrace to the console
=> fix: Assorted small fixes

OpoLua/View Controllers/BrowserViewController.swift
Since we're shipping this to the App Store, we need to guard against some programs appearing in the index for download.
=> fix: Block NSFW content from the Psion Software Index

src/compiler.lua, src/tcompiler.lua
* Incorrect arguments to CLEARFLAGS, DATETIM$
* Wrong return type for PEEKB, PEEKW
* Lack of zero arguments check for MIN/MAX/MEAN/STD/SUM/VAR
* Lack of argument count check for mPOPUP
fixes #465.
=> Assorted compiler fixes

OpoLua/Info.plist
This changes the SIS file type identifier from `org.opolua.sis` to a more generic (but invented) `com.psion.sis` in an attempt to establish an identifier that can be shared between different apps. In the near term, the goal is to come up with an identifier that can be shared with Reconnect.
=> fix: Use common SIS file type identifier

OpoLua.xcodeproj/project.pbxproj, OpoLua/Extensions/SisInstallError.swift, OpoLua/Model/FileSystem.swift, OpoLua/Model/Installer.swift, OpoLua/Model/Program.swift, README.md, src/cmdline.lua, src/compile.lua, src/defaultiohandler.lua, src/dumpsis.lua, src/init.lua, src/opl.lua, src/recognizer.lua, src/runtime.lua, src/sis.lua, swift/OpoIoHandler.swift, swift/PsiLuaEnv.swift
Much of which is internal. Most visible improvements are to the dumpsis.lua command which now:
* allows creation of installation receipts ('stubs')
* can uninstall SIS files
* shows FileText prompts from SIS files that have them
=> feat: Improved SIS file handling

docs/_includes/footer.html, docs/_includes/navigation.html, docs/css/style.css
This includes a drive-by fix to rename the 'Release Notes' link in the header to 'Releases'.
=> docs[website]: Move the privacy policy link into the footer

OpoLua/Info.plist
This change re-adds support for the legacy `org.opolua.sis` file type as a work around for macOS confusions and moves both types to be imported not exported to avoid stealing ownership.
=> fix: Improve SIS file type associations

src/dumpaif.lua
Because the bitmaps in a .opa aren't in MBM format in the first place.
=> fix: Don't attempt to reconstruct an MBM when dumpaif-ing a .opa
