inseven/opolua

OpoLua.xcodeproj/project.pbxproj, OpoLua/Extensions/UIImage.swift, OpoLua/Model/Directory.swift, OpoLua/View Controllers/DirectoryViewController.swift, OpoLua/Views/PixelView.swift
There are still a few layout tweaks required for landscape.
=> feat: Grid view for the directory listing

OpoLua/View Controllers/Installer/InstallerSummaryViewController.swift, OpoLua/View Controllers/LibraryViewController.swift
Delegates should always be weak.
=> fix: Potential memory leak in the installer and library views

OpoLua.xcodeproj/project.pbxproj, OpoLua/AppDelegate.swift, OpoLua/View Controllers/DestinationPickerViewController.swift, OpoLua/View Controllers/DirectoryViewController.swift, OpoLua/View Controllers/Installer/InstallerIntroductionViewController.swift, OpoLua/View Controllers/Installer/InstallerViewController.swift
This change also adds a drive-by fix to improve the layout of the installer introdcution view.
=> fox: Pick different installation destinations

.github/workflows/build.yaml, .gitmodules
This change updates the documentation build to use an Ubuntu runner to allow for parallel builds.
=> ci: Parallelise documentation builds

OpoLua.xcodeproj/project.pbxproj, OpoLua/Licenses/Diligence.txt, OpoLua/View Controllers/SettingsView.swift
This includes a drive-by fix to update the Diligence dependency.
=> fix: Include the version number in support emails

README.md, src/opx/system.lua
Which fixes a bunch more cases of #202.
=> fix: Don't error on SetForegroundByThread or LogonToThread(0)

src/dialog.lua, src/menu.lua
MenuPane refactored to be much more OO
fixes #156
=> feat: menus now support vertical scrollbars

src/cp1252.lua, src/dumpsis.lua, src/sis.lua
Also filters garbage data from buggy SIS files
=> fix: dumpsis now outputs UTF-8 filenames

src/includes/printer_oxh.lua, src/memory.lua, src/ops.lua, src/opx/gprinter.lua, src/opx/printer.lua, src/runtime.lua
=> fix: realloc, stub opx.printer and opx.gprinter

OpoLua.xcodeproj/project.pbxproj, src/includes/dbase_oxh.lua, src/includes/sysram1_oxh.lua, src/includes/systinfo_oxh.lua, src/opx/dbase.lua, src/stack.lua
Also added some missing oxhs and pbxproj definitions.
Fixes #325
=> fix: Support dbase.opx

scripts/build.sh, src/init.lua
This includes some drive-by syntax cleanup in the build script.
=> build: Compile the lua source to check for syntax errors

OpoLua.xcodeproj/project.pbxproj, OpoLua/View Controllers/AllProgramsViewController.swift, OpoLua/View Controllers/BrowserViewController.swift, OpoLua/View Controllers/DirectoryViewController.swift, OpoLua/View Controllers/LibraryViewController.swift, OpoLua/View Controllers/RunningProgramsViewController.swift
This change also includes a drive-by refactor that introduces a common `BrowserViewController` superclass for all program browsers.
=> fix: Combined add toolbar button in the browser views

OpoLua.xcodeproj/project.pbxproj, OpoLua/View Controllers/BrowserViewController.swift
This change catches up to the updated PsionSofwareIndexSwift dependency.
=> refactor: Rename the Software Index library

OpoLua/View Controllers/BrowserViewController.swift
This change catches up to the latest version of the Psion Software Index with improved appearance on larger screens.
=> fix: Improve software index on larger displays

src/modules/toolbar.lua
to cater for series 7 apps. fixes #396.
=> fix: Allow more than 4 toolbar buttons

src/fns.lua, src/ops.lua
=> fix: Implement BOOKMARK/GOTOMARK/KILLMARK

src/modules/toolbar.lua
=> fix: fix toolbar refactor fail

src/compiler.lua, src/ops.lua, src/opx/date.lua, src/tcompiler.lua
For megg32. Also fixed broken CURSOR logic. fixes #376
=> fix: System.opx GetFileTime

OpoLua/Model/Program.swift, OpoLua/View Controllers/ProgramViewController.swift, OpoLua/Views/AutoOrientView.swift, swift/OpoIoHandler.swift
There's quite a bit more work to do here, but this is is a first-cut of the plumbing required to respond to the on-screen text field and cursor.
=> fix: Ensure the software keyboard doesn't cover focused text boxes

src/compile.lua, src/compiler.lua, src/tcompiler.lua
=> fix: compiler: support ADDR on array subscripts

docs/_layouts/default.html, docs/status/index.markdown
I anticipate this getting fairly long as we check more programs. Filtering should make it more manageable.
=> docs: Support filtering the status table

OpoLua/View Controllers/BrowserViewController.swift
Preparatory work for a 1.2 release.
=> fix: Only show the software index in debug builds

docs/404.html, docs/404.md, docs/css/style.css
This removes the custom styling from the 404 page and adopts the layout from the rest of the site.
=> docs[website]: Clean up the appearance of the 404 page

src/opl.lua, src/ops.lua
Which doesn't matter to the Swift backend but does for the Qt one...
=> refactor: gCLOCK() should be passing a nil info

src/init.lua
=> fix: typo in touint32
